
# Taller 1 - Métodos Numéricos
## 2020 - 1er cuatrimestre
### Objetivo

El objetivo del trabajo es completar los siguientes puntos relacionados con los temas de factorización LU, de Cholesky y matrices ortogonales. 

La idea es ejercitar tanto los conceptos teóricos como poder llevarlos a la práctica usando `numpy`

#### Evaluación:

- Implementar cada uno de los siguientes ejercicios, haciendo que corran los respectivos tests.

- Coloquio con los docentes durante la clase (preguntas sobre el enunciado y el código). Justificar las respuestas


# Ejercicio 0
## Precalentamiento en Numpy

En estos ejercicios vamos a trabajar un poco con `numpy` para afianzar su uso en para lo que viene luego.

Arranquemos con algunos fáciles:

### 0.1.1: Creación de matriz

Crear la siguiente matriz usando [`np.array`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html), consultar su tipo y dimensión.

$$
A =
\begin{pmatrix}
	1 & 2 & 3 \\
    4 & 5 & 6 \\
	7 & 8 & 9
\end{pmatrix}
$$



In [0]:
import numpy as np


"""
TODO: Crear matriz A
"""
A = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

print(type(A))
print(A.dtype)
print(A.shape)

<class 'numpy.ndarray'>
int64
(3, 3)


### 0.1.2: Creación de matriz nula

Crear una matriz de ceros de $\mathbb{R}$<sup>$3\times3$</sup>. 

**Nota:** Usar la función [np.zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)

In [0]:
"""
TODO: Crear matriz de ceros
"""

B = np.zeros((3, 3))

assert(B.shape == (3, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 0.1.3: Creación de matriz identidad

Crear una matriz identidad de $\mathbb{R}$<sup>$3 \times 3$</sup>.

**Nota:** Usar la función [np.eye](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html).


In [0]:
"""
TODO: Crear matriz identidad
"""
B = np.eye(3)

B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 0.1.4: Iterar sobre una matriz

Imprimir cada elemento de la matriz A (de izquierda a derecha, de arriba hacia abajo)

Usar [range](https://docs.python.org/3.6/library/stdtypes.html#typesseq-range) y [np.shape](https://docs.python.org/3.6/library/stdtypes.html#typesseq-range)

In [0]:
"""
TODO: Completar 
"""

for i in range(np.shape(A)[0]):
  for j in range(np.shape(A)[1]):
    print(A[i][j])

1
2
3
4
5
6
7
8
9


## 0.2: Operaciones

Vamos a hacer algunas operaciones sobre matrices. Sean $A$ y $B$ las siguientes matrices:

In [0]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 1, 1],
    [0, 1, 1],
    [0, 0, 1]
])

### 0.2.1 Suma de matrices

Calcular $C = A + B$

In [0]:
"""
TODO: Completar código
"""

#Método 1: iterativamente

C = np.zeros((3, 3))

for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    C[i][j] = A[i][j] + B[i][j]

print(C)
# Método 2: vectorialmente (mucho mejor!)

C = A + B

C

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

### 0.2.1 Multiplicación de matrices

Calcular $C = A B$.

**Nota:** Ver documentación de [np.matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul) (función que implementa el operador `@`).

In [0]:
"""
TODO: Calcular el producto de A y B
"""

# Método 1

C = np.zeros((3, 3))


# Método 2: mejor
C = A @ B


assert(np.allclose(C, np.array([
    [1, 3, 6],
    [4, 9, 15],
    [7, 15, 24]
])))

AssertionError: ignored

### 0.3: Igualdad de matrices:





![alt text](https://pm1.narvii.com/5991/b3ff9d95cc8cd7916b1d1b432fcd3bf79b6a62e2_hq.jpg)

**Nota**: Para los que no hayan visto "Indiana Jones y la última Cruzada": el protagonista llega a un lugar protegido por un templario donde hay muchas copas, y sólo una es el "Santo Grial".

Pueden ver la secuencia acá: en [español](https://www.youtube.com/watch?v=-EvzYURFdR0&t=73s) o el [original](https://www.youtube.com/watch?v=A0TalLrtZ24&t=15s).




Acá, también tenemos que elegir sabiamente...


Sean dos matrices, $B$ y $C$, producto de distintos cálculos. ¿Cómo podemos verificar que son iguales?


In [0]:
A = np.array([
    [.1, 0, 0],
    [0, .1, 0],
    [0, 0, .1],
], dtype="float")

B = A + A + A

C = np.array([
    [.3, 0, 0],
    [0, .3, 0],
    [0, 0, .3],
], dtype="float")

Primero, imprimámoslas para ver qué tienen...

In [0]:
print(f"B = \n {B}")
print(f"C = \n{C}")


B = 
 [[0.3 0.  0. ]
 [0.  0.3 0. ]
 [0.  0.  0.3]]
C = 
[[0.3 0.  0. ]
 [0.  0.3 0. ]
 [0.  0.  0.3]]


¡Fantástico, todo parece andar bien! Veamos ahora si `B == C`

In [0]:
result = B == C

type(result)

numpy.ndarray

El resultado es un array, ya que `B == C` se efectúa elemento a elemento. 

No queremos eso. Podemos entonces hacer `(A == A.T).all()` que, dada una matriz de booleanos, verifica si todos sus elementos son `True`.

In [0]:
(B == C).all()

False

Las dos matrices son distintas? 😱

Hemos cometido uno de los pecados capitales de Métodos Numéricos: comparación por igualdad entre dos números de punto flotante.

![](https://media1.tenor.com/images/4988bf571adbd4edc5df437a8530eba4/tenor.gif?itemid=5056977 "chess")


### IMPORTANTE: NUNCA COMPARAR PUNTOS FLOTANTES POR IGUALDAD

Recordemos que, producto de la limitada precisión de estos números, siempre debemos comparar con cierta "tolerancia". `numpy` nos provee de una función que nos permite hacer esto: [np.allclose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html)

**Nota**: Si quieren entender un poco más algunas sutilezas de cómo Python maneja los puntos flotantes (más allá del estandar de la IEEE) pueden ver [este link](https://docs.python.org/3/tutorial/floatingpoint.html).

In [0]:
# Esto es lo mismo que hacer 
# np.isclose(B, C).all()
np.allclose(B, C)

True

¡Bien! Has elegido sabiamente, c

![](https://media1.tenor.com/images/c69f043088acef4637ecce5de0e3bed9/tenor.gif?itemid=13257298 "wisely")



### 0.3.1: Creación de matriz aleatoria

Crear una matriz de $\mathbb{R}$<sup>$3\times 3$</sup> uniformemente distribuida en el intervalo $(0, 1)$.

Usar [np.random.rand](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html)

In [0]:
A = None

A

### 0.3.2: Creación de matriz aleatoria con distribución $N(0, 1)$

Crear una matriz de $\mathbb{R}$<sup>$3\times3$</sup> tal que cada coordenada sea una variable con distribución $N(0, 1)$.

**Nota:** Usar la función [np.random.randn](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randn.html)

In [0]:
A = None

A

### 0.4: Slicing (¿Rebanado?)

Dada la matriz

$$
A =
\begin{pmatrix}
	1 & 2 & 3 \\
    4 & 5 & 6 \\
	7 & 8 & 9
\end{pmatrix}
$$

Vamos a realizar diferentes accesos a las submatrices de $A$. 

**Observación**: `numpy` maneja de manera distinta los arrays 1-dimensionales de los n-dimensionales. Tener esto siempre en cuenta!


### 0.4.1 Obtener la segunda fila de la matriz


In [0]:
"""
TODO: Completar código
""" 
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

fila = A[1]
assert(np.allclose(fila, np.array([4, 5, 6])))

### 0.4.2 Obtener la tercera columna de A

In [0]:
columna = A[:, 2]

assert(np.allclose(columna, np.array([3, 6, 9])))

### 0.4.3 Obtener submatriz

Obtener la submatriz

$$
\begin{pmatrix}
	1 & 2 \\
    4 & 5
\end{pmatrix}
$$

de la matriz $A$.


In [0]:
submatriz = A[:2, :2]

assert(np.allclose(
    submatriz, 
    np.array([
       [1, 2],
       [4, 5]
    ])
))

### 0.5: Reshape:

Muchas veces ocurre que tenemos listas de números que queremos convertir en una matriz, o bien arrays de una dimensión (vectores) que queremos convertirlos en matrices fila/columna ya que `numpy` suele efectuar de manera distinta las operaciones en el caso 1-dimensional o 2-dimensional.

Para ello, aprenderemos a hacer darle una nueva "forma" al array. Para ello, utilizaremos la función [reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) de `numpy`.


### 0.5.1: Lista a matriz
Convertir el array $L = [1, 2, \ldots, 7, 8, 9]$ en la matriz de $\mathbb{R}$<sup>$3 \times 3$</sup>

$$
A =
\begin{pmatrix}
	1 & 2 & 3 \\
    4 & 5 & 6 \\
	7 & 8 & 9
\end{pmatrix}
$$



**Sugerencia:** Verificar las dimensiones de las matrices y/o vectores usando [shape](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.shape.html).

In [0]:
# range es un iterador ... para convertirlo en una lista concreta, hay que hacer esto

nums = list(range(1, 10))

L = np.array(nums)

"""
TODO: Completar código
"""
A = np.reshape(L, (3, 3))

print(A)

assert(np.allclose(
    A, np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 0.5.2: Vectores columna

1. ¿Qué nos da el `shape` de obtener la primera columna de $A$ con `A[:, 0]`?
2. Si `v = A[:, 0]` ¿cuál es el resultado de `v @ v.T`? ¿Por qué ocurre esto? (ver documentación de [np.matmul](https://numpy.org/devdocs/reference/generated/numpy.matmul.html?highlight=matmul#numpy.matmul))
3. Utilizar `reshape` para convertir `v` en una matriz columna de $\mathbb{R}$<sup>`3 x 1`</sup>
**Nota:** reshape permite utilizar `-1` como comodín.

In [0]:
v = A[:, 0]

print(v @ v.T)

v = np.reshape(v, (3, 1))

print(v.shape)
print(v.shape == (1,3))
print(v.shape == (3,1))
print(v.shape == 3)


66
(3, 1)
False
True
False


In [0]:

"""
TODO: usar reshape para v como un vector columna
"""
mat_columna = np.reshape(v, (3, 1))


assert(mat_columna.shape == (3, 1))

### 0.6.1 Producto Interno

Calcular el producto interno entre la primera fila de $A$ y la tercera columna de $B$. 

**Nota:** Ver documentación de [np.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul).

In [0]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 1, 1],
    [0, 1, 1],
    [0, 0, 1]
])

""" 
TODO: Calcular el producto interno pedido
"""
prod_interno = A[0] @ B[:, 2]

assert(np.isclose(prod_interno, 6))

### 0.6.2 Producto Externo

Sean $u = (1, 2, 3)$, $v = (-1, 1, 2)$ (primera fila, y última columna de A y B respectivamente). Calcular la matriz $u v^T$ (el llamado producto externo entre $u$ y $v$).

¿Cuál es el rango columna de $u v^T$?

**Nota**: puede realizarse haciendo un reshape y luego @, o bien usando [np.outer
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html).



In [0]:

u = A[0, :]
v = B[:, 2]

print(u.shape, v.shape)

"""
TODO: Calcular el producto externo
"""
prod_externo = np.reshape(u, (3, 1)) @ np.reshape(v.T, (1, 3))

assert(np.allclose(prod_externo, np.array([
    [1,  1,  1],
    [2,  2,  2],
    [3,  3,  3]]
)))


(3,) (3,)


## Ejercicio 1

Repasar la definición de factorización LU. ¿Bajo qué condiciones podemos garantizar
que una matriz inversible tiene factorización LU? 

Completar la función `tiene_LU` que dada una matriz A, nos devuelve `True` si tiene factorización LU, o `False` en caso contrario.

**Tip**: considerar las funciones [np.shape](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.shape.html) para obtener las dimensiones de una matriz, y [np.linalg.det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html) para obtener el determinante de una matriz.


In [0]:
import numpy as np

eps = 1e-6

def tiene_lu(A):
    """
    Dada una matriz A, devuelve True si tiene descomposición LU, o False en caso contrario
    
    Argumentos:
    -----------
    
    A: np.array
        Matriz de floats

    Devuelve:
    ---------
    
    res: bool
        True si tiene LU, False caso contrario
    """
    
    """
    TODO: Completar la función
    """
    n = np.shape(A)[0]
    ans = True

    for i in range(n):
      if np.abs(np.linalg.det(A[:i, :i])) < eps:
        ans = False
    
    return ans


### Unittest

Corramos unos tests automatizados para ver si esto funciona. 

**PUEDEN SIMPLEMENTE IGNORAR ESTO**

**Obs 1**: A cada test le pondremos el decorador `@mntest` definido arriba. Necesitamos además setear en cada celda donde corramos tests la variable `tests` a `[]`.

**Obs 2**: No usaremos ninguna de las bibliotecas estándar de Python (`unittest` o `pytest`) puesto que no están pensadas para funcionar con Jupyter.

In [0]:
#Código para que corran los tests: (pueden ignorarlo)

import numpy as np
import math
import traceback


def mntest(func):
    global tests
    
    tests.append(func)    
    
    return func

def correr_tests():
    excepciones = []
    for test in tests:
        try:
            print("Corriendo {} ... ".format(test.__name__), end='')
            test()
            print("OK")
        except AssertionError as e:
            error_msg = traceback.format_exc()
            excepciones.append((test, error_msg))
            print("ERROR")
    
    if len(excepciones) > 0:
        print("\nErrores:\n")
        for (test, error_msg) in excepciones:
            print("En {}".format(test.__name__))
            print(error_msg)
    else:
        print("\n\nTodos los tests pasaron correctamente")

In [0]:
tests = []


@mntest
def testear_identidad_tiene_LU():
    A = np.identity(3)
        
    assert(tiene_lu(A))
    

@mntest
def testear_matriz_ceros_no_tiene_LU():
    A = np.zeros((3, 3))
        
    assert(not tiene_lu(A))
    
@mntest
def testear_matriz_no_inversible():
    A = np.ones((3, 3))
    
    assert(not tiene_lu(A))

@mntest 
def testear_matriz_permutacion_no_tiene_LU():
    A = np.array([
        [1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]
    ])
    
    assert(not tiene_lu(A))


correr_tests()

Corriendo testear_identidad_tiene_LU ... OK
Corriendo testear_matriz_ceros_no_tiene_LU ... OK
Corriendo testear_matriz_no_inversible ... OK
Corriendo testear_matriz_permutacion_no_tiene_LU ... OK


Todos los tests pasaron correctamente


## Ejercicio 2: Resolver LU por bloques



### ¿Cómo era esto de resolver en bloques?
Sea $A \in \mathbb{R}^{n \times n}$ a la cual le queremos calcular la factorización LU. Para ello, lo calcularemos en bloques en vez del método tradicional de triangulación. 

Supongamos que A tiene factorización LU; es decir podemos descomponerla en $L, U \in \mathbb{R}^{n \times n}$ escribiendo la descomposición en bloques de la forma:


$$
A = L U \\
$$

$$
\begin{pmatrix}
a_{11}   & A_{12}  \\
A_{21} & A_{22}
\end{pmatrix} = \begin{pmatrix}
1 & 0  \\
L_{21} & L_{22}
\end{pmatrix} \begin{pmatrix}
u_{11}   & U_{12}  \\
0 & U_{22}
\end{pmatrix}
$$

&nbsp;


donde $a_{11}, l_{11}, u_{11}$ son escalares, $A_{12} \in \mathbb{R}^{1 \times (n-1)}$ (vector fila), $L_{21} \in \mathbb{R}^{(n-1) \times 1}$

De aquí obtenemos las siguientes ecuaciones:

\begin{align*}
u_{11} &= a_{11} \\
U_{12} &= A_{12} \\
L_{21} &= \frac{A_{21}}{u_{11}}  \\
\end{align*}

Estas 3 ecuaciones nos permitirán despejar y obtener el contenido de estos 3 bloques. Ahora, nos queda la última ecuación:

$$
A_{22} = L_{21} U_{12} + L_{22} U_{22} \\
$$

Reescribiéndola, nos queda:
$$
A_{22} - L_{21} U_{12} = L_{22} U_{22} \\
$$

Y aquí, un pequeño salto de fe (esperemos razonable para los que ya hayan cursado Algo 2): si resolvemos la factorización LU de $A_{22} - L_{21} U_{12}$, podemos obtener los dos bloques que nos faltan.





**Ejercicio**:  Calcular LU en bloques para que tome una matriz $A \in \mathbb{R}^{n \times n}$ y nos devuelva $L$ y $U$, su descomposición LU correspondiente. 

La resolución tiene que ser *iterativa* pero puede convenir empezar a pensarlo en términos recursivos.

**RESPONDER**: ¿Cómo aseguran paso a paso que la matriz tenga factorización LU?

**Hint**: Ojo con la dimensión de los vectores. Si queremos multiplicar una matriz "columna", con una matriz "fila" tenemos que hacer reshape primero.

In [0]:
def lu_en_bloques(A):
    """
    Dada una matriz A, devuelve L, U 
    
    Argumentos:
    -----------
    
    A: np.array
        Matriz de floats

    Devuelve:
    ---------
    
    L, U: np.array
        Descomposición LU de A
        
    """
    
    """
    current_matrix es la matriz a la cual le estoy calculando LU
    
    Primero va a ser A, luego A22 - L21 * U21, ...
    """
    current_matrix = A.copy()
    
    """
    Vamos a ir "rellenando" paso a paso la factorización LU
    """
    L = np.zeros(A.shape)
    U = np.zeros(A.shape)
    
    n = A.shape[0]
    
    """
    Vamos a iterar desde 0 hasta n-1 e ir completando L y U
    de acuerdo a las ecuaciones antes explicadas
    """
    for i in range(n):
        """
        
        Observación: 
        
        En cada paso i estamos "llenando" las columnas y filas i-ésimas de L y U. Por eso tenemos que indexar por i
        
        Sin embargo, current_matrix la tenemos que indexar en 0 ya que es la matriz que vamos a ir
        "achicando" en dimensión. 
        
        """
        
        """
        TODO: Rellenar los valores de L[i, i] y U[i, i]
        """
        L[i, i] = 1
        U[i, i] = current_matrix[0, 0]
        """
        Caso "base": si es el final, no seguir
        """
        if i == n-1:
            break
        
        """
        TODO: Calcular los nuevos valores de U12 y L21
        """
        U[i, i+1:] = current_matrix[0, 1:]
        L[i+1:, i] = current_matrix[1:, 0] / U[i, i]
        
        """
        TODO: Calcular la matriz del caso "recursivo".
        
        Esto sería la nueva "A"
        
        Sugerencia: usar np.outer o hacer reshape
        """
        current_dim = current_matrix.shape[0]
        
        
        new_matrix = current_matrix[1:, 1:] - np.outer(L[i + 1:, i], U[i, i + 1:])

        """
        Asignamos la nueva matriz a calcular LU
        
        Nos aseguramos de que su dimensión se haya reducido en uno
        """
        current_matrix = new_matrix
        
        assert(current_matrix.shape == (current_dim-1, current_dim-1))

    return L, U

In [101]:
tests = []


@mntest
def testear_con_multiplo_identidad():
    A = 3 * np.identity(3)
    
    L, U = lu_en_bloques(A)
    
    assert(np.allclose(L, np.eye(3)))
    assert(np.allclose(U, 3*np.eye(3)))
    
    

@mntest
def testear_con_otra_matriz():
    L = np.array([
        [1, 0, 0],
        [1, 1, 0],
        [1, 1, 1],
    ])

    U = np.array([
        [1, 1, 1],
        [0, 2, 2],
        [0, 0, 3],
    ])

    A = L @ U
    
    L1, U1 = lu_en_bloques(A)
    
    assert(np.allclose(L1, L))
    assert(np.allclose(U1, U))

@mntest
def testear_con_otra_matriz2():
    A = np.array([
        [8, 2, 0],
        [4, 9, 4],
        [6, 7, 9],
    ])


    
    L1, U1 = lu_en_bloques(A)
    
    assert(np.allclose(L1@U1, A))

@mntest
def matriz_sin_LU():
    A = np.array([
        [0, 1, 0],
        [0, 1, 0],
        [0, 0, 1]
    ])


    
    L1, U1 = lu_en_bloques(A)
    
    assert(np.allclose(L1@U1, A))

    

correr_tests()


Corriendo testear_con_multiplo_identidad ... OK
Corriendo testear_con_otra_matriz ... OK
Corriendo testear_con_otra_matriz2 ... OK
Corriendo matriz_sin_LU ... ERROR

Errores:

En matriz_sin_LU
Traceback (most recent call last):
  File "<ipython-input-45-ab9080785aad>", line 19, in correr_tests
    test()
  File "<ipython-input-101-e434c09f7257>", line 62, in matriz_sin_LU
    assert(np.allclose(L1@U1, A))
AssertionError



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:65: RuntimeWarning: invalid value encountered in true_divide


## Ejercicio 3

Completar la función con un método para determinar si una matriz es ortogonal o no. 

En caso de serlo, explicar cómo se podría devolver un conjunto ortonormal de vectores a partir de la matriz.

**Agregar dos casos de test** probando con dos matrices ya conocidas: de rotaciones (Givens) y de reflexiones (Householder)

In [0]:
def es_ortogonal(A):
    """
    Devuelve True si A es ortogonal, False en otro caso
    
    
    Argumentos:
    ----------
    
    A: np.array
        
    Devuelve:
    ---------
    
    res: bool
        True si A ortogonal, False en otro caso
    """

    """
    TODO: Completar acá
    """

    return np.allclose(A.T, np.linalg.inv(A))

In [82]:
from math import cos, sin
tests = []

@mntest
def probar_con_identidad():
    A = np.eye(3)
    
    assert(es_ortogonal(A))
    
@mntest
def probar_con_rotacion():
    angle = math.pi/4
    """
    TODO: Escribir una matriz de rotación angle de 2x2 
    """
    A = np.array([
                  [np.cos(angle), -np.sin(angle)],
                  [np.sin(angle), np.cos(angle)]
    ])
    
    assert(es_ortogonal(A))

@mntest
def probar_con_reflexion():
    v = np.array([[1,1,1]])
    """
    TODO: Escribir la matriz de reflexión sobre el plano cuya normal es v
    """
    A = np.array([
                  [1, 0],
                  [0, -1]
    ])

    assert(es_ortogonal(A))

    
correr_tests()

Corriendo probar_con_identidad ... OK
Corriendo probar_con_rotacion ... OK
Corriendo probar_con_reflexion ... OK


Todos los tests pasaron correctamente


## Ejercicio 4

Sea $A \in \mathbb{R}^{n \times n}$, simétrica y no singular

### Ejercicio 4.1

Si $A$ tiene factorización $LU$, probar que tiene factorización $LDL^T$. ¿Son las dos $L$ iguales? 

#### SOLUCIÓN

Unas pequeñas pistas
Si $A = LU$ es simétrica, entonces 

\begin{align*}
A &= A^T \\
L U &= U^T L^T\\
\end{align*}

¿Qué forma tiene $U^T$? ¿Es el lado derecho una factorización LU? ¿Cómo la podemos convertir a una factorización LU? (sin calcular ninguna inversa, de ser posible)


<font color='red'>$U^\dagger$ es triangular inferior. No, porque $U^\dagger$ no tiene unos en la diagonal. $\left( U^\dagger L^\dagger \right)^\dagger = LU$, así que hay que transponer.</font>

### Ejercicio 4.2

Dada la factorización $A = LU$, ¿Cómo puedo calcular $D$ (de $LDL^T$) sin usar matrices inversas?



### SOLUCIÓN



<font color='red'>Si hacés Cholesky entonces obtenés $A=LL^\dagger=(\tilde{L}\sqrt{D})(\tilde{L}\sqrt{D})^\dagger=\tilde{L}D\tilde{L}^\dagger$

$A=LU = LDL^\dagger \implies U=DL^\dagger$, como $L^\dagger$ tiene unos en la diagonal entonces la diagonal de $U$ debe ser la diagonal de $D$.</font>

### Ejercicio 4.3



Completar la función `chol_from_LU` para que tome una matriz A y devuelva la matriz correspondiente a su factorización de Cholesky utilizando como base la factorización LU de `A`, sin calcular ninguna matriz inversa en el medio.

En el caso de que la matriz no tenga factorización de Cholesky, **debe generar un error mediante `raise ValueError`**

    
**Hint**: considerar las funciones [np.diag](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.diag.html) y [np.sqrt](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.sqrt.html).

Dada una matriz `A` podemos obtener una matriz que tenga la diagonal de `A` y 0 en las demás posiciones mediante `np.diag(np.diag(A))`


In [0]:
def es_simetrica(A):
    """
    TODO: Completar esta función
    """
    return np.allclose(A.T, A)

def chol_from_lu(A):
    """
    Devuelve la L de Cholesky a través de la factorización LU de la matriz A
    
    En caso de que no tenga LU o que no tenga Cholesky, lanza ValueError
    
    Argumentos:
    ----------
    
    A: np.array
        Matriz a factorizar
    
    Devuelve:
    ---------
    
    L: np.array
        Factorización de Cholesky de A
    """
    if not es_simetrica(A):
        raise ValueError("Matriz no simétrica")
    
    
    L, U = lu_en_bloques(A)
    """
    TODO: Completar acá
    """
    D_raiz = np.zeros(U.shape)
    for i in range(U.shape[0]):
      D_raiz[i, i] = np.sqrt(U[i, i])
    
    new_L = L @ D_raiz

    return new_L

In [103]:
tests = []


@mntest
def testear_con_identidad():
    A = np.eye(3)
    L = chol_from_lu(A)
    
    # Cholesky es la identidad también :-)
    assert(np.allclose(A, L))
    

@mntest
def testear_con_multiplo_identidad():
    A = 4 * np.eye(3)
    L = chol_from_lu(A)
    
    # Cholesky es la identidad también :-)
    assert(np.allclose(L, 2* np.eye(3)))
    
@mntest
def testear_con_matriz_no_sdp():
    A = np.array([
        [1, 0, 0],
        [0, -1, 0],
        [0, 0, 2]
    ])
    try:
        L = chol_from_lu(A)
        raise AssertionError("Tiene que lanzar excepción")
    except ValueError as e:
        pass

@mntest
def testear_con_matriz():
    L1 = np.array([
        [1, 0, 0],
        [2, 2, 0],
        [4, 4, 4]
    ])
    
    A = L1 @ L1.T
    L = chol_from_lu(A)
    assert(np.allclose(L, L1))

correr_tests()


Corriendo testear_con_identidad ... OK
Corriendo testear_con_multiplo_identidad ... OK
Corriendo testear_con_matriz_no_sdp ... ERROR
Corriendo testear_con_matriz ... OK

Errores:

En testear_con_matriz_no_sdp
Traceback (most recent call last):
  File "<ipython-input-45-ab9080785aad>", line 19, in correr_tests
    test()
  File "<ipython-input-103-1eea488f18cb>", line 30, in testear_con_matriz_no_sdp
    raise AssertionError("Tiene que lanzar excepción")
AssertionError: Tiene que lanzar excepción



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: RuntimeWarning: invalid value encountered in sqrt


## Ejercicio 5: Opcional

Supongamos que tenemos $A \in \mathbb{R}^{n \times n}$. Si generamos $x_1, \ldots x_k \in \mathbb{R}^n$ vectores aleatorios ¿cómo podemos chequear "probabilísticamente" que $A$ es simétrica definida positiva?

Enunciar un método basado en la generación de vectores aleatorios para mostrar que una matriz no es definida positiva o para ganar más confianza en que sí lo es. 

**Opcional**: Tratar de pensar la implementación sin for, ni while 

**Opcional 2**: ¿Se les ocurre algún ejemplo en el que fallaría este método?

**Tip**: 
Las funciones [np.diagonal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diagonal.html) y [np.any](https://docs.scipy.org/doc/numpy/reference/generated/numpy.any.html) también pueden ser de ayuda.

In [0]:

def tiene_sdp_vectores_aleatorios(A, n):
    """
    Chequea que la matriz sea SDP usando método probabilístico de vectores aleatorios
    
    Argumentos:
    ----------
    
    A: np.array
        Matriz a verificar su condición de SDP
       
    n: int
        Cantidad de vectores a 
    
    Devuelve:
    ---------
    
    res: bool
        True si no encontró si A es SDP bajo este método probabilístico
    """
    if not es_simetrica(A):
        return False
    
    """
    TODO: Generar vectores aleatorios y verificar si alguno rompe la condición de DP
    """ 
    

    return None  

Con este ejemplo debería andar:

In [0]:
tests = []


@mntest
def testear_con_identidad():
    A = np.eye(3)
    assert(tiene_sdp_vectores_aleatorios(A, 10000))
    
    

@mntest
def testear_con_matriz_no_sdp():
    A = np.array([
        [1, 0, 0],
        [0, -1, 0],
        [0, 0, 1],
    ])
    
    assert(not tiene_sdp_vectores_aleatorios(A, 10000))
    
    
@mntest
def testear_con_otra_matriz_no_sdp():
    A = np.array([
        [1, 0, 0],
        [0, 1, 2],
        [0, 2, 1],
    ])
    
    assert(not tiene_sdp_vectores_aleatorios(A, 10000))
    
    

correr_tests()
