In [1]:
#H Hacemos los imports correspondientes a numpy
import numpy as np
import numpy.linalg as lng

### Ejemplos
Algunos ejemplos de operaciones matriciales básicas disponibles en numpy

In [2]:
# Distintas maneras de inicializar una matriz
A = np.array([[1,2],[3,4]])
B = np.array(np.mat('9 10; 11 12')) # Subclase
C = np.array([[5,6],[7,8]], dtype=float)

# Para los vectores usamos matrices por columnas
v = np.array([[11],[12]])
w = np.array(np.mat('17; 18')) # Subclase
x = np.array([21,22,23,24], ndmin=4)

In [3]:
# Matrices especiales
I = np.eye(3) # Identidad de 3x3
D = np.diag([77,90]) # Matriz diagonal
N = np.zeros((3,4)) # Matriz nula de 3x3

# Operaciones basicas entre matrices y vectores
A + B       # Suma
A - B       # Resta
A @ B       # Producto de matrices
A @ v       # Producto de matriz por vector
3.2 * A     # Producto por escalar
A**2        # Potencia
A.T         # Traspuesta (transpose())
lng.inv(A)  # Inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Ejercicio 1
Dados x<sub>1</sub>, ..., x<sub>n</sub> una muestra de una variable aleatoria, implementar rutinas que calculen la media y la varianza utilizando operaciones vectoriales.

In [13]:
def mean(x):
    # COMPLETAR
    
def var(x):
    # COMPLETAR
    

In [ ]:
N = 4
x = np.array(np.random.rand(N,1))
print("x:" + str(x) + "\n media: " + str(mean(x)) + " varianza: " + str(var(x)))
assert(np.abs(mean(x) - np.mean(x)) < 1e-6 )
assert(np.abs(var(x) - np.var(x)) < 1e-6 )
print("OK")

### Ejercicio 2
Sea A matriz en R<sup>m×n</sup><br>
1. Demostrar que A<sup>t</sup> A y AA<sup>t</sup> son simétricas<br>
2. Implementar una rutina que dada una matriz cuadrada verifique si la misma es simétrica

In [3]:
def esSimetrica(A):    
    # COMPLETAR
    


A: 
[[1 2]
 [2 6]
 [3 7]
 [4 8]]
B: 
[[0.37783374 0.53908518 0.82090228 0.07025189]
 [0.66712579 0.51538912 0.74848172 0.90433636]
 [0.73436199 0.26534833 0.68524983 0.84354985]
 [0.59545841 0.90847219 0.36393029 0.46011308]]
OK


In [ ]:
A = np.array([[1,2],[2,6],[3,7],[4,8]])
B = np.random.rand(4,4)

print("A: \n"  + str(A))
print("B: \n" + str(B))
assert(esSimetrica(A @ A.T))
assert(esSimetrica(B.T @ B))
print("OK")

### Ejercicio 3

Analizar la función implementada en el item anterior con la matriz B generada de la siguiente forma:

`A = np.random.rand(4,4)
B = A.T * A * 0.1 / 0.1`

Analizar el resultado, revisar la implementación y (eventualmente) reimplementar la función.

In [5]:
D = np.array(np.diag([1,2]))
I = np.array(np.eye(5))
A = np.random.rand(4,4)

print(A)
assert(not(esSimetrica(A)))

# Ojo! usamos @ para el producto matricial
assert(esSimetrica(A.T@(A*0.10)/0.10))
assert(esSimetrica(D) and esSimetrica(I))
print("Ok")

[[0.71574789 0.19197766 0.90793541 0.8197275 ]
 [0.83168167 0.78640367 0.35078215 0.50343803]
 [0.75128037 0.71664088 0.47936216 0.81561268]
 [0.13453611 0.69429678 0.31643302 0.45533332]]
Ok


### Ejercicio 4
Sean A, B en R<sup>n×n</sup>, con n par y B triangular inferior,
1. Realizar la multiplicación AB por bloques, partiendo ambas matrices en bloques de tamaño n/2.
2. Implementar una rutina que realice la multiplicación por bloques, evitando cuentas innecesarias.

In [19]:
def block_multiplication(A,B): 
    
    n = A.shape[0]
    assert(n % 2 == 0)
    
    # Completar
    A11 = None
    A12 = None
    A21 = None
    A22 = None
    
    B11 = None
    B12 = None
    B21 = None
    B22 = None
    
    C_11 = None
    C_12 = None
    C_21 = None
    C_22 = None
    
    return np.block([[C_11,C_12],[C_21,C_22]])


Ok


In [ ]:
N = 4
A = np.array(np.random.rand(N,N))
B = np.array(np.random.rand(N,N))
assert(np.allclose(A @ B,block_multiplication(A,B)))

print("Ok")